apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-login-config
data:
  MYSQL_DB_HOST: "mysql-login.default.svc.cluster.local"
  MYSQL_DB_PORT: "3306"
  MYSQL_DB_NAME: "login_db"
  CHAT_ENDPOINT: "35.231.213.14"
