apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-login-config
data:
  MYSQL_DB_HOST: {{ .Values.login.mysql.host | quote }}
  MYSQL_DB_PORT: {{ .Values.login.mysql.port | quote }}
  REDIRECT_HOST: {{ .Values.login.redirectHost | quote }}
