apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-login-deployment
spec:
  replicas: {{ .Values.login.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: spring-login
  template:
    metadata:
      labels:
        app: spring-login
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup {{ .Values.login.mysql.host }}; do echo waiting for mysql; sleep 2; done']
      containers:
        - name: login-service
          image: "{{ .Values.weCloud.imageRegistry.gcp }}/{{ .Values.login.image }}:{{ .Values.login.tag }}"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spring-login-config
            - secretRef:
                name: login-secret
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
