# TODO: Implement the deployment configuration for the profile service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-profile-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-profile
  template:
    metadata:
      labels:
        app: spring-profile
    spec:
      imagePullSecrets:                 
        - name: gcr-json-key
      containers:
        - name: profile-service
          image: {{ .Values.weCloud.imageRegistry.gcp }}/{{ .Values.profile.image }}:{{ .Values.profile.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: profile-secret  
                  key: mysql-username
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: profile-secret
                  key: mysql-password
            - name: MYSQL_DB_HOST
              value: "{{ .Values.profile.mysql.host }}"
            - name: MYSQL_DB_PORT
              value: "{{ .Values.profile.mysql.port }}"
