apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-profile-deployment
spec:
  replicas: {{ .Values.profile.replicaCount }}
  selector:
    matchLabels:
      app: spring-profile
  template:
    metadata:
      labels:
        app: spring-profile
    spec:
      containers:
        - name: profile
          image: {{ .Values.weCloud.imageRegistry.gcp }}/{{ .Values.profile.image }}:{{ .Values.profile.tag }}
          ports:
            - containerPort: {{ .Values.profile.containerPort }}
          env:
            - name: MYSQL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: spring-profile-config
                  key: MYSQL_DB_HOST
            - name: MYSQL_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: spring-profile-config
                  key: MYSQL_DB_PORT
            - name: MYSQL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: profile-secret
                  key: mysql-username
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: profile-secret
                  key: mysql-password
