apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.login.releaseName }}-deployment
spec:
  replicas: {{ .Values.login.replicaCount }}
  selector:
    matchLabels:
      app: spring-login
  template:
    metadata:
      labels:
        app: spring-login
    spec:
      containers:
      - name: login-service
        image: {{ .Values.weCloud.imageRegistry.gcp }}/{{ .Values.login.image }}:{{ .Values.login.tag }}
        ports:
        - containerPort: {{ .Values.login.service.targetPort }}
        envFrom:
        - configMapRef:
            name: spring-login-config
        - secretRef:
            name: login-secret
        env:
        - name: MYSQL_DB_USER
          valueFrom:
            secretKeyRef:
              name: login-secret
              key: mysql-username
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: login-secret
              key: mysql-password

