weCloud:
  imageRegistry:
    gcp: "gcr.io/gcp-docker-kubernetes-486615" # TODO: Specify your GCP Artifact Registry

profile:
  repository: "profile-service"
  image: "profile-service"
  tag: "1.0.0"
  mysql:
    host: "mysql-profile.default.svc.cluster.local"
    user: "profileuser"
    password: "ProfilePass123"
    port: "3306"
  # TODO: Specify values used in profile service manifests

chat:
  repository: "chat-service"
  image: "chat-service"
  tag: "1.0.0"
  mysql:
    host: "mysql-profile.default.svc.cluster.local"
    user: "chatuser"
    password: "ChatPass123"
    port: "3306"
  redis:
    host: "redis-service.default.svc.cluster.local"
    port: "6379"
  # TODO: Specify values used in chat service manifests
  profileEndpoints: "spring-profile-service.default.svc.cluster.local" # This value should be used in configMap-chat.yaml


login:
  repository: "login-service"
  image: "login-service"
  tag: "1.0.0"
  mysql:
    host: "mysql-profile.default.svc.cluster.local"
    user: "loginuser"
    password: "LoginPass123"
    port: "3306"
  redirectIP: "35.231.220.196"
  # TODO: Specify values used in login service manifests

# Below are the values used in the redis service
# DO NOT MODIFY
redis:
  image: "redis:7"
  host: "redis-service"
  password: "SuperSecretRedisPassword"
  passwordSecret: "redis-secret"
  passwordKey: "REDIS_PASSWORD"
  port: "6379"
  containerPort: 6379
  topic: "/topic/messages"
  service:
    port: 6379
    targetPort: 6379
