{{- if eq .Values.global.environment "gcp" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-chat-config
data:
  MYSQL_DB_HOST: {{ .Values.chat.mysql.host | quote }}
  MYSQL_DB_PORT: {{ .Values.chat.mysql.port | quote }}
  MYSQL_DB_NAME: "chat_db"
  SPRING_REDIS_HOST: {{ .Values.redis.host | quote }}
  SPRING_REDIS_PORT: {{ .Values.redis.port | quote }}
  RAW_TOPIC_MESSAGE: {{ .Values.redis.topic | quote }}
  LIST_OF_PROFILE_ENDPOINTS: "{{ .Values.chat.profileEndpoints.local }},http://{{ .Values.chat.profileEndpoints.azure }}/profile"
{{- end }}
