apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.profile.releaseName }}-deployment
spec:
  replicas: {{ .Values.profile.replicaCount }}
  selector:
    matchLabels:
      app: spring-profile
  template:
    metadata:
      labels:
        app: spring-profile
    spec:
      containers:
      - name: profile-service
        {{- if eq .Values.global.environment "gcp" }}
        image: {{ .Values.weCloud.imageRegistry.gcp }}/{{ .Values.profile.image }}:{{ .Values.profile.tag }}
        {{- else }}
        image: {{ .Values.weCloud.imageRegistry.azure }}/{{ .Values.profile.image }}:{{ .Values.profile.tag }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.profile.service.targetPort }}
        envFrom:
        - configMapRef:
            name: spring-profile-config
        - secretRef:
            name: profile-secret
        env:
        - name: MYSQL_DB_USER
          valueFrom:
            secretKeyRef:
              name: profile-secret
              key: mysql-username
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: profile-secret
              key: mysql-password
        resources:
          requests:
            cpu: {{ .Values.profile.hpa.cpuRequest }}

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.profile.releaseName }}-autoscaling
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.profile.releaseName }}-deployment
  minReplicas: {{ .Values.profile.hpa.minReplicas }}
  maxReplicas: {{ .Values.profile.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.profile.hpa.targetCPUUtilizationPercentage }}

