{{- if eq .Values.global.environment "gcp" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.chat.releaseName }}-deployment
spec:
  replicas: {{ .Values.chat.replicaCount }}
  selector:
    matchLabels:
      app: spring-chat
  template:
    metadata:
      labels:
        app: spring-chat
    spec:
      containers:
      - name: chat-service
        image: {{ .Values.weCloud.imageRegistry.gcp }}/{{ .Values.chat.image }}:{{ .Values.chat.tag }}
        ports:
        - containerPort: {{ .Values.chat.service.targetPort }}
        envFrom:
        - configMapRef:
            name: spring-chat-config
        - secretRef:
            name: chat-secret
        env:
        - name: MYSQL_DB_NAME
          value: "chat_db"
        - name: MYSQL_DB_HOST
          value: {{ .Values.chat.mysql.host | quote }}
        - name: MYSQL_DB_PORT
          value: {{ .Values.chat.mysql.port | quote }}
        - name: SPRING_REDIS_HOST
          value: {{ .Values.redis.host | quote }}
        - name: SPRING_REDIS_PORT
          value: {{ .Values.redis.port | quote }}
        - name: RAW_TOPIC_MESSAGE
          value: {{ .Values.redis.topic | quote }}
        - name: LIST_OF_PROFILE_ENDPOINTS
          value: {{ .Values.chat.profileEndpoints | quote }}
        - name: SPRING_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.redis.passwordSecret }}
              key: {{ .Values.redis.passwordKey }}
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: chat-secret
              key: mysql-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: chat-secret
              key: mysql-password
        resources:
          requests:
            cpu: {{ .Values.chat.hpa.cpuRequest }}

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.chat.releaseName }}-autoscaling
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.chat.releaseName }}-deployment
  minReplicas: {{ .Values.chat.hpa.minReplicas }}
  maxReplicas: {{ .Values.chat.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.chat.hpa.targetCPUUtilizationPercentage }}
{{- end }}

