apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.profile.releaseName }}-deployment
spec:
  replicas: {{ .Values.profile.replicaCount }}
  selector:
    matchLabels:
      app: spring-profile
  template:
    metadata:
      labels:
        app: spring-profile
    spec:
      containers:
      - name: profile-service
        image: {{ .Values.weCloud.imageRegistry.gcp }}/{{ .Values.profile.image }}:{{ .Values.profile.tag }}
        ports:
        - containerPort: {{ .Values.profile.service.targetPort }}
        envFrom:
        - configMapRef:
            name: spring-profile-config
        - secretRef:
            name: profile-secret
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: profile-secret
              key: mysql-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: profile-secret
              key: mysql-password

