{{- if eq .Values.global.environment "gcp" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-chat-deployment
  labels:
    app: spring-chat
spec:
  selector:
    matchLabels:
      app: spring-chat
  template:
    metadata:
      labels:
        app: spring-chat
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: chat-service
          image: {{ .Values.weCloud.imageRegistry.gcp }}/{{ .Values.chat.image }}:{{ .Values.chat.tag }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
          resources:
            requests:
              cpu: 200m
          envFrom:
            - configMapRef:
                name: spring-chat-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://{{ .Values.chat.mysql.host }}:{{ .Values.chat.mysql.port }}/chatdb
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: mysql-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: mysql-password
            - name: REDIS_HOST
              value: "{{ .Values.chat.redis.host }}"
            - name: REDIS_PORT
              value: "{{ .Values.chat.redis.port }}"

---


apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spring-chat-autoscaling
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-chat-deployment
  minReplicas: {{ .Values.chat.hpa.minReplicas }}
  maxReplicas: {{ .Values.chat.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.chat.hpa.targetCPUUtilizationPercentage }}
{{- end }}
