metadata:
  name: wecloud-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /login(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: spring-login-service
            port:
              number: 80
      - path: /profile(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: spring-profile-service
            port:
              number: 80
