{{- if eq .Values.global.environment "gcp" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.passwordSecret }}
type: Opaque
data:
  {{ .Values.redis.passwordKey }}: {{ .Values.redis.password | b64enc | quote }}
{{- end }}
