# TODO: Implement the secret for profile service
apiVersion: v1
kind: Secret
metadata:
  name: profile-secret
type: Opaque
stringData:
  mysql-password: {{ .Values.profile.mysql.password | quote }}
  mysql-username: {{ .Values.profile.mysql.user | quote }}
