apiVersion: v1
kind: Secret
metadata:
  name: login-secret
type: Opaque
stringData:
  mysql-password: {{ .Values.login.mysql.password | quote }}
  mysql-username: {{ .Values.login.mysql.user | quote }}
