# TODO: Implement the service configuration for the chat service
apiVersion: v1
kind: Service
metadata:
  name: spring-chat-service
spec:
  type: NodePort
  selector:
    app: spring-chat
  ports:
    - port: 80
      targetPort: 8080

