global:
  environment: azure

login:
  chatEndpoint: "http://34.46.244.57/chat"
  redirectHost: "34.46.244.57"
  mysql:
    host: mysql-login
    port: "3306"
    user: "loginuser"
    password: "LoginPass123"

profile:
  mysql:
    host: mysql-profile
    port: "3306"
    user: "profileuser"
    password: "ProfilePass123"
