global:
  environment: azure

login:
  chatEndpoint: "http://136.119.155.165/chat"
  redirectHost: "136.119.155.165"
  mysql:
    host: mysql-login
    port: "3306"
    database: "login_db"
    user: "loginuser"
    password: "LoginPass123"

profile:
  mysql:
    host: mysql-profile
    port: "3306"
    database: "profile_db"
    user: "profileuser"
    password: "ProfilePass123"
