global:
  environment: azure

login:
  chatEndpoint: "34.9.146.235"
  redirectHost: "34.9.146.235"
  mysql:
    host: mysql-login
    port: "3306"
    database: "login_db"
    user: "loginuser"
    password: "LoginPass123"

profile:
  mysql:
    host: mysql-profile
    port: "3306"
    database: "profile_db"
    user: "profileuser"
    password: "ProfilePass123"
