global:
  environment: "gcp"

weCloud:
  imageRegistry:
    gcp: gcr.io/gcp-docker-kubernetes-486615 

profile:

  releaseName: spring-profile
  replicaCount: 1
  repository: profile-service
  image: profile-service
  tag: "1.0.0"
  containerPort: 8080
  service:
    type: NodePort 
    port: 80
    targetPort: 8080
  mysql:
    host: mysql-profile
    port: "3306"
    user: profileuser
    password: ProfilePass123
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
    cpuRequest: 100m

chat:

  releaseName: spring-chat
  replicaCount: 1
  image: group-chat-service
  tag: "1.0.4"
  repository: group-chat-service
  containerPort: 8080
  service:
    type: NodePort
    port: 80
    targetPort: 8080
  mysql:
    host: mysql-chat
    port: "3306"
    user: "chatuser"
    password: "ChatPass123"
  profileEndpoints: "spring-profile-service.default.svc.cluster.local:80" 
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
    cpuRequest: 100m

login:

  releaseName: spring-login
  replicaCount: 1
  image: login-service
  tag: "1.0.4"
  repository: login-service
  containerPort: 8080
  service:
    type: NodePort
    port: 80
    targetPort: 8080
  mysql:
    host: mysql-login
    port: "3306"
    user: "loginuser"
    password: "LoginPass123"
  redirectHost: "136.119.155.165" 
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
    cpuRequest: 100m

redis:
  image: "redis:7"
  host: "redis-service"
  password: "SuperSecretRedisPassword"
  passwordSecret: "redis-secret"
  passwordKey: "REDIS_PASSWORD"
  port: "6379"
  containerPort: 6379
  topic: "/topic/messages"
  service:
    port: 6379
    targetPort: 6379
